import type { Metadata } from "next";
import { PropostasProvider } from "@/context/PropostasContext";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR">
      <body>
        <PropostasProvider>{children}</PropostasProvider>
      </body>
    </html>
  );
}


